### PR TITLE
Build distribution and upload to PyPI

### PR DESCRIPTION
**Pull request by NoraLoose**
This PR sets up a github workflow that builds C-Star locally, which creates distribution archives under the `dist/` directory. These are the files that will be uploaded to PyPI when publishing a new release.

### CODE REVIEW

**Comment by dafyddstephenson** [comment]
Thanks Nora! Are we able to test this before merging? I think #147 might be potentially problematic here

**Comment by NoraLoose** [comment]
@dafyddstephenson definitely! The "Build distribution / test-built-dist" test that fails in the CI is that exact test. I think it fails for the same reason as #147.

**Comment by NoraLoose** [comment]
Obviously we won't merge before this issue is resolved. :)

**Comment by dafyddstephenson** [comment]
ah sorry, I'm debilitated by jetlag right now! I saw the workflow is only triggered on push to main and thought we'd have to merge to check it - didn't notice it was also on PR. I was hoping #168 might fix the static install issue as there's no longer a dynamically generated python file in the configuration, but no dice...

**Comment by NoraLoose** [comment]
@TomNicholas once #147 is fixed, all tests in this PR should pass. So we could try to fix the issue as part of this PR?

**Review by TomNicholas — APPROVED** [review]

**Comment by TomNicholas** [comment]
#179, #180, and #181 together seemed to fix this

**Pull request merged**
