### PR TITLE
Also run `test_roms_tools_integration.py` in CI

### LINKED ISSUE #104: Testing CI not running roms-tools integration tests
Presumably this line means the tests CI job is not currently running the file `test_roms_tools_integration.py` introduced in https://github.com/CWorthy-ocean/C-Star/pull/81?

https://github.com/CWorthy-ocean/C-Star/blob/bfac303efa5ff76f98f76c61f42245b6d4e00004/.github/workflows/tests.yaml#L48

### PR DESCRIPTION
**Pull request by TomNicholas**
Should close #104

### CODE REVIEW

**Comment by TomNicholas** [comment]
@dafyddstephenson it's unclear to me from the printed output whether or not this successfully ran the roms integration tests.

**Comment by dafyddstephenson** [comment]
I don't really know what's happening here but a couple of points:
1. It looks like `test_roms_tools_integration.py` is not even starting up
2. Just as well, as `test_roms_tools_integration.py` _will not work_ on github without access to certain datasets. For now it is just meant to be run locally.

**Comment by dafyddstephenson** [comment]
Can this be closed? After #54 goes in I'll try (as an exercise) and update it to do what this PR aims to do using our new test domain.

**Comment by TomNicholas** [comment]
if `test_roms_tools_integration.py` isn't even supposed to be run then yeah close this.

**Pull request closed without merging**
