### PR TITLE
Documentation for how to use ROMS-Tools to generate input files

### PR DESCRIPTION
**Pull request by NoraLoose**

### CODE REVIEW

**Comment by NoraLoose** [comment]
Do you want to have a look, @dafyddstephenson? You may know this already, but a nice way to see the rendered notebook in the documentation is to click "Details" next to the last check:

Screenshot 2024-09-27 at 10 40 58 AM

**Comment by dafyddstephenson** [comment]
I did not know that, thanks! Any tips on how to review? The notebook won't load as it's so long

**Comment by NoraLoose** [comment]
Can you click the purple button
Screenshot 2024-09-27 at 11 20 08 AM

and then "docs/roms_tools_input.ipynb"?

You should be able to review in there.

**Comment by dafyddstephenson** [comment]
yep, the giant button that says "Review" on it did the trick 😅...

**Comment by NoraLoose** [comment]
<p>Yes, ROMS does not know any land, just shallow water. Anything on land is filled with the <code>hmin</code> value, which here is set to the default of 5m. Should I explain this in this notebook, or too much? </p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805076'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Sounds good.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805096'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Oops, thanks!</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805109'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Then we are back to the legal problem that we cannot distribute the TPXO data.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805175'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>We could point them to where they can download it themselves?</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805175'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>ROMS-Tools only supports an outdated version of the TPXO atlas, though, see <a href="https://github.com/CWorthy-ocean/roms-tools/issues/141" target="_blank">https://github.com/CWorthy-ocean/roms-tools/issues/141</a>.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805175'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dafyddstephenson** [comment]
<blockquote>We could point them to where they can download it themselves?</blockquote><p>yep that's what I meant</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805175'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Good idea.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805150'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805201'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805224'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>I added a link to where they can download themselves, with the disclaimer that ROMS-Tools currently only works for TPXO9v2.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805175'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805275'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>Sounds good.</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805318'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NoraLoose** [comment]
<p>They currently sit on my personal scratch on derecho. Should we make a project space?</p>

---

 <a href='https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805252'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by dafyddstephenson — APPROVED** [review]

**Comment by dafyddstephenson** [comment]
> They currently sit on my personal scratch on derecho. Should we make a project space?
> 
> [View entire conversation](https://app.reviewnb.com/CWorthy-ocean/C-Star/pull/110/discussion/#comment-2379805252) on ReviewNB

I think they must have come from the CESM group, so they should be traceable to their origin there?

**Comment by NoraLoose** [comment]
> I think they must have come from the CESM group, so they should be traceable to their origin there?

No, `ROMS-Tools` accepts a post-processed version of the original CESM files (which I made), where the post-processing steps are:
1. Compute climatology from monthly data
2. Regrid from POP onto regular lat-lon grid

Step 1 is skipped for the CESM surface data - instead, I simply select the last 20 years of data.

**Comment by dafyddstephenson** [comment]
In that case it would be nice to make a project directory (in fact perhaps we should aim to make this thing go on all supported HPC systems?) if it's not too much of a faff...

**Comment by NoraLoose** [comment]
> In that case it would be nice to make a project directory (in fact perhaps we should aim to make this thing go on all supported HPC systems?) if it's not too much of a faff...

Okay, I will open a separate issue for this (#111). Once we have this set up, we can add the location to this notebook, maybe in a future PR?

**Comment by NoraLoose** [comment]
This should be good to merge. We can always modify this later on!

**Pull request merged**
